# Generated by Django 3.1.1 on 2020-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
        migrations.AddField(
            model_name='userbook',
            name='image',
            field=models.ImageField(default='default.png', help_text='Designates the users book images.', upload_to='book_images', verbose_name='Book Image'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='isbn',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
